### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by MDFL64** [glua/gm_voxelate#1]
Swad wanted to do a thing. Not sure if still wants to do thing, and I still have some shit on my plate, but here's a list potential features for UPDATE.

**Possible Goals:**
- Add support for sparse / arbitrary sized voxel maps.
- Add a way to trace through arbitrary sized maps.
- Add some kind of rendering support for arbitrary sized maps.
- Move all the lua shit to actual Lua files. The way the lua portion is loaded now is jank as fuck.
- TRY TO improve traces and deal with precision errors.
- Just flat out disable smooth texturing until...
- Try to get array textures working, either on source's terms or via graphics API hackery.
- Make networking work without dipping into the Lua context. Need to ask my nerds how2do.

There's a lot of other crap that COULD BE useful later, but I think this is a good list to start with.

**Non-Goals:**
- Getting actual physics to work on arbitrary sized maps. Traces should be fine.
- Any kind of inventory bullshit
- Javascript support.
- For now I probably won't bother with any kind of linux or OSX support.

**Comment by MDFL64** [comment]
Looks like the underlying graphics API doesn't even support array textures? Fuckin nice.

**Comment by SwadicalRag** [comment]
yes am still interested​
I have an exam next week so I'm studying for it in the mean time

**Comment by mcd1992** [comment]
I'd do a Lunix if you faggos can make the code somewhat platform-independent.

**Comment by MDFL64** [comment]
Pretty sure it already is, mostly. I remember there was some weird fuckery with the SDK. I mostly just didn't want to deal with it, but if daddy's got it covered that's 💯

**Comment by bmwalters** [comment]
and i can 🍎 it up

**Comment by MDFL64** [comment]
I just started porting this over to garrysmod_common + sourcesdk-minimal. Hopefully will be done sometime tomorrow.

**Comment by SwadicalRag** [comment]
I did too and I died

**Comment by MDFL64** [comment]
Getting VS set up again then going to bed. Getting shit to build is about half of the battle, as usual.

**Comment by SwadicalRag** [comment]
i got everything to work except fastlz for some reason, so i tried to move it outside the src folder and tried to get it working again

if you want my premake, here it is

```lua
newoption({
	trigger = "gmcommon",
	description = "Sets the path to the garrysmod_common (https://github.com/danielga/garrysmod_common) directory",
	value = "path to garrysmod_common directory"
})

local gmcommon = _OPTIONS.gmcommon or os.getenv("GARRYSMOD_COMMON")
if gmcommon == nil then
	error("you didn't provide a path to your garrysmod_common (https://github.com/danielga/garrysmod_common) directory")
end

include(gmcommon)

CreateWorkspace({name = "voxelate"})
	defines({
		"RAD_TELEMETRY_DISABLED"
	})

	CreateProject({serverside = true})
		language("C++11")

		includedirs("../fastlz")
		links({"fastlz"})

		IncludeSDKCommon()
		IncludeSDKTier0()
		IncludeSDKTier1()
		IncludeSDKTier2()
		IncludeSDKMathlib()
		-- IncludeSDKRaytrace()
		IncludeSteamAPI()
		IncludeDetouring()
		IncludeScanning()
		IncludeLuaShared()

	CreateProject({serverside = false})
		language("C++11")

		includedirs("../fastlz")
		links({"fastlz"})

		IncludeSDKCommon()
		IncludeSDKTier0()
		IncludeSDKTier1()
		IncludeSDKTier2()
		IncludeSDKMathlib()
		-- IncludeSDKRaytrace()
		IncludeSteamAPI()
		IncludeDetouring()
		IncludeScanning()
		IncludeLuaShared()

	project("fastlz")
		kind("StaticLib")
		files({
			"../fastlz/fastlz.c",
			"../fastlz/fastlz.h",
		})
```

also I had to include glua headers like so: 

```cpp
#ifndef GLUA_HEADER_MEMES
#define GLUA_HEADER_MEMES

#define GMOD_ALLOW_DEPRECATED

// TODO, stop using the fucking gayry lua interface
// #define LUA state->luabase

#include "GarrysMod/Lua/Interface.h"

#endif
```

also in metaman's source engine headers you'll want this: 

```cpp

		if (!LOADINTERFACE("engine", INTERFACEVERSION_VENGINESERVER, iface_sv_ents))
			return false;
```

**Comment by SwadicalRag** [comment]
also to use SDKMathLib you'll need to manually modify metaman's gmcommon lib until this PR gets merged

https://github.com/danielga/garrysmod_common/pull/4/

**Comment by SwadicalRag** [comment]
also i was having super weird issues with vs2013/vs2015 not liking c++11

**Comment by SwadicalRag** [comment]
but yes, mainly couldn't figure out why the fuck this error appeared
![here](https://cdn.discordapp.com/attachments/152162730244177920/309922844890890240/unknown.png)

maybe gmodule sensei @danielga knows more
