### ISSUE TITLE
tabs or 4 spaces?

### ISSUE THREAD

**Issue by SwadicalRag** [glua/gm_voxelate#17]
my branch is a mess rn guys

**Comment by bmwalters** [comment]
tabs

**Comment by bmwalters** [comment]
no wait, this is c++. let's use semicolons

```
int main() {
;;;;return 0;
}
```

**Comment by bmwalters** [comment]
```
int main() {
;;;;return 0;
}
```

**Comment by SwadicalRag** [comment]
but @meepdarknessmeep prefers spaces

**Comment by bmwalters** [comment]
I don't see any git commits from a meepdarknessm

**Comment by SwadicalRag** [comment]
hush hush

**Comment by MDFL64** [comment]
I usually assume my editor is smart enough to keep everything consistent.

Then my editor just shits the bed and we're left with a total clusterfuck.

**Comment by SwadicalRag** [comment]
we're already in a state of clusterfuck

**Comment by SpencerSharkey** [comment]
install an .editorconfig and stick to tabs, then anyone can decide how to view their code (as 2 space, 4 spaces, etc)

**Comment by notcake** [comment]
spaces on prime numbered lines and tabs everywhere else

this is a good compromise

**Comment by SwadicalRag** [comment]
let's just remove all whitespace

**Comment by xaviergmail** [comment]
Spaces.

- is space
\t__ is tab

\t__hi_some_thing = 2;

**Comment by xaviergmail** [comment]
Spaces.
```
hi_lolol = 2;
hi2      = 2; (6 spaces)
hi2\t    = 2; (1 tab + 2 spaces)
```

mixing tabs & spaces for alignment will be the doom of us all

**Comment by notcake** [comment]
how about em-spaces

that way everyone is equally happy

**Comment by SwadicalRag** [comment]
now ur talking

**Comment by MDFL64** [comment]
By power vested in me as chief asshole I vote tabs for indentation and fuck you for alignment.

My previous theory that modern text editors are smart enough to figure out what to do has proven very wrong.

On a similar note, are line endings an issue at all? VS has been bitching at me.

If we do a mass-conversion we're going to need to coordinate it well.

**Comment by SpencerSharkey** [comment]
LF-style line endings

**Comment by notcake** [comment]
unicode paragraph separators for line endings

**Comment by mcd1992** [comment]
spacer master race

**Comment by SwadicalRag** [comment]
already converted everything to tabs

**Comment by mcd1992** [comment]
Shit fucking project, forking now.... 💢

**Comment by SwadicalRag** [comment]
you have push access genius

**Comment by mcd1992** [comment]
Got me
