### ISSUE TITLE
Finish rewriting the Lua portion of this module

### ISSUE THREAD

**Issue by SwadicalRag** [glua/gm_voxelate#22]
- [x] Basic lua framework
 - [x] Voxelate networking wrapper
 - [x] VoxelWorld entity
 - [x] Voxel config networking
 - [x] VoxelWorld initial chunk networking
 - [x] VoxelWorld chunk updates networking
 - [x] Other stuff I've missed

**Comment by SwadicalRag** [comment]
I have opted for voxel world saving/loading to be done from c++

**Comment by MDFL64** [comment]
Agree
