### ISSUE TITLE
Upgrade to enetpp

### ISSUE THREAD

**Issue by SwadicalRag** [glua/gm_voxelate#31]
https://github.com/jseward/enetpp

just a set of headers that does multithreaded dicksucking for us

**Comment by SwadicalRag** [comment]
Mostly done

things left to do/take into account/fix:
 - [x] `lua_network_connect` is no longer synchronous and doesn't return an error
 - [ ] bind a function to lua which exposes `client.is_connecting_or_connected`
 - [x] ALTERNATIVELY figure out some way to ensure the client is connected to the server
 - [x] VoxNetworkConnect hook no longer passes in numeric IP (it passes in a string now)
 - [x] debugging

**Comment by SwadicalRag** [comment]
I am too tired to continue working tonight

**Comment by SwadicalRag** [comment]
I know I told you I'd try and keep the changes small and not hacky, but i truly fucked up: I used ENet inappropriately in a multithreaded context. It's not always thread safe, and that's why networking was all sorts of fucked.

so, sorry in advance @birdbrainswagtrain if you were expecting small changes 😢

**Comment by MDFL64** [comment]
god damn it

**Comment by MDFL64** [comment]
1. Not surprised by the whole "i figured out threads are hard" thing.
2. ENetPP looks like a good library ~but I'm not sure why you've seen fit to modify it?~ Guess it's okay.
3. It's really hard for me to keep the whole "unfuck it by the end of the weekend" thing on track if stuff like this keeps happening.
4. Not sure what these commits are about "RAII claiming data" but one of us is very wrong and I'm not sure who it is at this point.

**Comment by MDFL64** [comment]
I'm just going to go play Overwatch to delay the point in time when I inevitably come unhinged.

**Comment by MDFL64** [comment]
Okay, the murderous rage has mostly worn off. Regardless, please don't add another dependency while I'm sleeping again. One of the reasons this turned into such a clusterfuck was that you decided to redo networking while we were still in the middle of redoing storage, and now you've decided to redo networking **again**. I'm okay with the choice, but damn I was pissed when I woke up.

**Comment by SwadicalRag** [comment]
Firstly, I'd like to apologize a second time. I know it's difficult as it is to write and debug a gmod module, let alone work with code either of us aren't familiar with. This is the reason working slow doesn't seem like such a bad idea, so everyone is on the same page.

It isn't going to be easy. We're past the point of working on a basic voxel module. We're working on something completely insane, and it's not going to be easy anymore. I knew full well what I would be getting into when I replaced enet with enetpp. I knew full well what would happen if I left the implementation half completed. But I completely disagree that I shouldn't have made the changes overnight.

If I didn't do anything about bad multithreading, you might have wasted hours debugging enet to no avail. If I left this issue as is, porting to enetpp may have seemed a large task at hand and we may have gone in the wrong direction by procrastinating and working on something else.

I want to reiterate that both of us live in two different time zones, and we need to make full use of that. I'm really short of time and the weekend is all I have, really, and I expect it's the same with you as well.

I am totally prepared for breaking commits overnight: it's the way I work. But it's also understandable that in a project like this, breaking changes become really hard to keep track of if they're done on a daily basis.

But, you know, if we take the easy way out, and the well known path of slow and steady progress, I fear this project will never be complete, and both of us may lose our motivation.

It's going to be hard, and the best thing we can do is embrace it and give it the best efforts we can.

**Comment by SwadicalRag** [comment]
Now that project semantics are out of the way, as for RAII: all I did was remove stack based vars and make them in the heap since enet takes ownership of a lot of things passed into it.

**Comment by MDFL64** [comment]
> enet takes ownership of a lot of things passed into it.

What gave you that idea? Is this documented anywhere?

I used the tried and tested RTFSC strategy which indicated buffers are copied unless you specify otherwise...
```
    if (flags & ENET_PACKET_FLAG_NO_ALLOCATE)
      packet -> data = (enet_uint8 *) data;
    else
    if (dataLength <= 0)
      packet -> data = NULL;
    else
    {
       packet -> data = (enet_uint8 *) enet_malloc (dataLength);
       if (packet -> data == NULL)
       {
          enet_free (packet);
          return NULL;
       }

       if (data != NULL)
         memcpy (packet -> data, data, dataLength);
    }
```

**Comment by SwadicalRag** [comment]
oh shit, I read the code wrong: so it COPIES our data to its own pointer?

I jumped to conclusions since I was getting heap corruption crashes

**Comment by SwadicalRag** [comment]
The heap corruption occurred probably because enet wasn't thread safe too

**Comment by MDFL64** [comment]
Fair enough. I've done a few commits and now I'm just trying to figure out why chunk networking is badly borked. Probably my fault.

**Comment by SwadicalRag** [comment]
chunk networking was actually seriously fucked last time: enet was jizzing all over the heap and breaking other shit

**Comment by MDFL64** [comment]
looks good 2 me
