### ISSUE TITLE
Memory Leek (Probably?)

### ISSUE THREAD

**Issue by MDFL64** [glua/gm_voxelate#35]
Pretty sure my crashes were due to a memory leek.

![](http://i.imgur.com/RpcZGE7.jpg)

Chunks weren't being deleted on the server so that may have been an issue.

**Comment by SwadicalRag** [comment]
damn i was going to post a photo of a leek

**Comment by SwadicalRag** [comment]
Why are chunks even being deleted serverside? We don't have code to unload chunks yet???

**Comment by MDFL64** [comment]
Module unload. Chunk deletion was disabled because it would try to delete physics objects that don't exist.

**Comment by MDFL64** [comment]
I'll just have it delete worlds when the entities are deleted.

**Comment by SwadicalRag** [comment]
ah

**Comment by SwadicalRag** [comment]
![yey](http://i.imgur.com/6UdW3Sv.png)
