### ISSUE TITLE
Get working loonix build

### ISSUE THREAD

**Issue by MDFL64** [glua/gm_voxelate#37]
Guurgle tried this morning and had some mad issues with the sourcenet files. I can probably get shit set up on my server if nobody else wants to do this.

**Comment by ghost** [comment]
I can provide ssh access to my build environment if needed.

**Comment by SwadicalRag** [comment]
DAIJOUBU™️ @mcd1992 promised!

daddy will help us out

**Comment by SwadicalRag** [comment]
i did it nvm

**Comment by mcd1992** [comment]
nice
