### ISSUE TITLE
how do I compile this now?

### ISSUE THREAD

**Issue by SwadicalRag** [glua/gm_voxelate#47]
did the shaders change anything and do I have to install extra dependencies?

**Comment by MDFL64** [comment]
I wouldn't even bother with the shader branch right now. I just figured out texture sampling but lighting is still very wrong.

**Comment by MDFL64** [comment]
For future reference:

You will need to copy the source/shaders/shaders directory into the Garrysmod/garrysmod directory.

If you're actually building shaders, instructions are in source/shaders/readme.txt

No further actions should be required if not building shaders themselves, but you might need to re-run premake to link with the shader lib.
