### ISSUE TITLE
Remove lighting from voxel rendering

### ISSUE THREAD

**Issue by MDFL64** [glua/gm_voxelate#49]
Should get more consistent lighting if it were controlled exclusively through lua.

**Comment by SwadicalRag** [comment]
lighting from lua? I am lost.

**Comment by MDFL64** [comment]
Just ambient light, fancy shit is not on the menu yet.

**Comment by SwadicalRag** [comment]
ah aww

**Comment by MDFL64** [comment]
Done, still need to add lighting code back to testbed though.
