### ISSUE TITLE
Project Management Apps

### ISSUE THREAD

**Issue by MDFL64** [glua/gm_voxelate#7]
Submit yer ballots
--------------------
- Trello - Currently used. I'd rather switch to something else. 👍 
- Waffle.io - I'm a fan, basically a fancy UI over github issues. 😄 
- Github Project - Never used before. Anyone have an opinion? 🎉 
- Some Other Hipster Shit 👎

**Comment by bmwalters** [comment]
GitHub projects (sucks but it's integrated) > Trello > nothing at all > *

**Comment by MDFL64** [comment]
I made a test board to see how Github Projects work. Looks basically the same as waffle.io, but integrated better.

**Comment by notcake** [comment]
Atlassian JIRA for maximum enterprise

**Comment by bmwalters** [comment]
atlassian trello for medium enterprise

**Comment by SwadicalRag** [comment]
text files for the TRUE enterprise experience

**Comment by notcake** [comment]
https://www-03.ibm.com/software/products/en/rtc

**Comment by mcd1992** [comment]
Redmine?

**Comment by SpencerSharkey** [comment]
I was going to say it but @mcd1992 said it first.

**Comment by bmwalters** [comment]
I'd say GitHub projects for real, anything external is more of a hassle

**Comment by meepen** [comment]
Using anything but issues is retarded

**Comment by xaviergmail** [comment]
gitlab

**Comment by meepen** [comment]
Ur all dun

**Comment by bmwalters** [comment]
projects is backed by issues, meep

**Comment by meepen** [comment]
Then use issues

**Comment by meepen** [comment]
Let's use Trello for bugs GitHub for source slack for internal working
discord for community outreach and mailing list for discussions forums for
announcements and IRC for talking

**Comment by bmwalters** [comment]
and BitTorrent for releasing versions? 😛

**Comment by MDFL64** [comment]
Fuck it. We'll just use issues for now and I'll use waffle.io on top of it when I deem it necessary.

**Comment by bmwalters** [comment]
What's wrong with GitHub projects?

**Comment by SwadicalRag** [comment]
everything
